api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
#    patch_formats:
#        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    # Custom congif
    title: 'Forum API'
    description: 'T120B165 Saityno taikomųjų programų projektavimas'
    show_webby: false