gesdinet_jwt_refresh_token:
    user_provider: security.user.provider.concrete.app_user_provider
    cookie:
        sameSite: lax
        path: /
        domain: null
        httpOnly: true
        secure: true