#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check # TODO
gesdinet_jwt_refresh_token:
    path:       /api/token/refresh # TODO
    controller: gesdinet.jwtrefreshtoken::refresh